name: publish project with core-bundle
on:
  workflow_call:
    inputs:
      branch:
        description: 'Set the branch to use for release'
        type: string
        required: false
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Build with core-bundle
        uses: forcedotcom/bundle-publish-scripts/.github/actions/buildWithCoreBundle@main
      - name: Publish a Package
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN --verbose
          npm publish --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
