name: publish project with core-bundle
on:
  workflow_call:
    inputs:
      branch:
        description: "Set the branch to use for release"
        type: string
        required: false
        default: "main"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build.yml
        with:
          branch: ${{ inputs.branch }}
      - uses: ./.github/workflows/publish.yml
